package mocks

import mock "github.com/stretchr/testify/mock"
import withtheflow "github.com/bradleyjkemp/withtheflow"

// WorkflowRunner is an autogenerated mock type for the WorkflowRunner type
type WorkflowRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: funcname, args
func (_m *WorkflowRunner) Run(funcname string, args interface{}) interface{} {
	ret := _m.Called(funcname, args)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, interface{}) interface{}); ok {
		r0 = rf(funcname, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// SetFlowHandlers provides a mock function with given fields: _a0
func (_m *WorkflowRunner) SetFlowHandlers(_a0 map[string]withtheflow.FlowHandler) withtheflow.WorkflowRunner {
	ret := _m.Called(_a0)

	var r0 withtheflow.WorkflowRunner
	if rf, ok := ret.Get(0).(func(map[string]withtheflow.FlowHandler) withtheflow.WorkflowRunner); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(withtheflow.WorkflowRunner)
		}
	}

	return r0
}
