// Code generated by protoc-gen-go.
// source: fibonacci.proto
// DO NOT EDIT!

/*
Package fibonacci is a generated protocol buffer package.

It is generated from these files:
	fibonacci.proto

It has these top-level messages:
	FibStepArg
	Result
*/
package fibonacci

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FibStepArg struct {
	Index int64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
}

func (m *FibStepArg) Reset()                    { *m = FibStepArg{} }
func (m *FibStepArg) String() string            { return proto.CompactTextString(m) }
func (*FibStepArg) ProtoMessage()               {}
func (*FibStepArg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FibStepArg) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Result struct {
	N int64 `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func init() {
	proto.RegisterType((*FibStepArg)(nil), "FibStepArg")
	proto.RegisterType((*Result)(nil), "Result")
}

func init() { proto.RegisterFile("fibonacci.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcb, 0x4c, 0xca,
	0xcf, 0x4b, 0x4c, 0x4e, 0xce, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0x72,
	0xcb, 0x4c, 0x0a, 0x2e, 0x49, 0x2d, 0x70, 0x2c, 0x4a, 0x17, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x4b,
	0x49, 0xad, 0x90, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0x94, 0xc4, 0xb8, 0xd8, 0x82,
	0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x84, 0x78, 0xb8, 0x18, 0xf3, 0xa0, 0x72, 0x8c, 0x79, 0x49, 0x6c,
	0x60, 0x23, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xe2, 0xeb, 0xd7, 0x55, 0x00, 0x00,
	0x00,
}
