// Code generated by protoc-gen-go.
// source: fibonacci.proto
// DO NOT EDIT!

/*
Package fibonacci is a generated protocol buffer package.

It is generated from these files:
	fibonacci.proto

It has these top-level messages:
	Data
	Result
*/
package fibonacci

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	NMinus1 int64 `protobuf:"varint,1,opt,name=nMinus1" json:"nMinus1,omitempty"`
	N       int64 `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
	Index   int64 `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetNMinus1() int64 {
	if m != nil {
		return m.NMinus1
	}
	return 0
}

func (m *Data) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *Data) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Result struct {
	Index int64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	N     int64 `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Result) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func init() {
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*Result)(nil), "Result")
}

func init() { proto.RegisterFile("fibonacci.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcb, 0x4c, 0xca,
	0xcf, 0x4b, 0x4c, 0x4e, 0xce, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe1, 0x62, 0x71,
	0x49, 0x2c, 0x49, 0x14, 0x92, 0xe0, 0x62, 0xcf, 0xf3, 0xcd, 0xcc, 0x2b, 0x2d, 0x36, 0x94, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x71, 0x85, 0x78, 0xb8, 0x18, 0xf3, 0x24, 0x98, 0xc0, 0x62,
	0x8c, 0x79, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x12, 0xcc, 0x60, 0x11, 0x08,
	0x47, 0x49, 0x87, 0x8b, 0x2d, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04, 0x21, 0xcf, 0x88, 0x24, 0x8f,
	0x6a, 0x46, 0x12, 0x1b, 0xd8, 0x6a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xcd, 0x63,
	0x17, 0x8d, 0x00, 0x00, 0x00,
}
